var facts = ["The study of snakes is termed ophiology.",
"Extraction of material by washing with a solvent is elution.",
"Underwater players hit a puck in the sport of octopush.",
"Burk is known for co-discovering biotin.",
"A particle made of three quarks is a baryon.",
"The Sanctuary of Nemesis is located in Rhamnous.",
"The Navajo language belongs to the Na-Dené family.",
"Rudimentary saddles were developed by Scythians.",
"Flatbread from Sweden is called tunnbröd.",
"The sport invented in Fascist Italy was volata.",
"The only moon that has a magnetosphere is Ganymede.",
"A roundhouse punch in taekwondo is called Dolyo Jireugi.",
"The atoll Aldabra is located in Seychelles.",
"The hobby of collecting postcards is deltiology.",
"The founder of the Mali Empire is Keita.",
"Alignment of three celestial objects is a syzygy.",
"Japan is divided into 47 prefectures.",
"A tribe divided in half according to descent is a moiety.",
"Shane Warne is famous for playing cricket.",
"Insertion of one word in the middle of another is tmesis.",
"Federal judge John Wood was murdered by Harrelson.",
"The author of 'Thunder Among the Leaves' is Bastos.",
"Myanmar is the only source of the rare mineral painite.",
"The root-like structure at the base of algae is a holdfast.",
"The stick used in the game of shinty is a caman.",
"The chanted, Hawaiian creation story is 'Kumulipo.'",
"Thin mirrors used to split beams of light are pellicles.",
"The city sieged by the Mongols in 1258 was Baghdad.",
"The star of 'The Scarlet Empress' was Dietrich.",
"A small projection from a bird's wing is an alula.",
"The term bluegown once referred to a beggar.",
"Diwali occurs during the Hindu month of Kartik.",
"Revolving a circle in three dimensions produces a torus.",
"Substituting a phrase with a close associate is metonymy.",
"In alquerque, the number of starting pieces is 12.",
"The variant of mancala played in Uganda is called omweso.",
"The property of directional dependence is anisotropy.",
"Linear-beam vacuum tubes used as amplifiers are klystrons.",
"The first genomically sequenced fish was the pufferfish.",
"A poem written for a bride is an epithalamium.",
"Sunspots became very rare during the Maunder Minimum.",
"One nation that became independent in 1821 was Honduras.",
"A yantok is used in the sport called eskrima.",
"The gelatinous substance under a turtle's lower shell is calipee.",
"Early Japanese immigrants to the U.S. were called issei.",
"The geographical range of a taxon is divided in vicariance.",
"The secret language of Irish Travellers is Shelta.",
"Words superordinate to more specific words are hypernyms.",
"The Latin phrase for an unconfirmed statement is ipse dixit.",
"One type of Scandinavian mythical creature is a skrat.",
"The Protoplasmic Theory was proposed by Schultze.",
"The capital city of Fiji is called Suva.",
"Muktuk is made out of bowhead whale skin.",
"Marine animals that move without currents are nektons.",
"An appetite for non-nutritive substances is cittosis.",
"The area between the lungs is the mediastinum.",
"The smallest insect species is the fairyfly.",
"Excessive use of the letter 'm' is mytacism.",
"The cape that marks the westernmost point in Asia is Baba.",
"One-twentieth of a typesetting point is a twip.",
"An eye disease that distorts the cornea is keratoconus.",
"The longest freshwater beach in the world is Wasaga Beach.",
"Animals' restlessness before migration is called zugunruhe.",
"A village council in India is called a panchayat.",
"Sawh is an accomplished Trinidadian urologist.",
"Extreme weight loss and muscle atrophy is cachexia.",
"A derivative in Newtonian calculus is a fluxion.",
"The comic character Shiera Saunders is Hawkgirl.",
"The sport kabbadi derives its name from Tamil.",
"Heavy, ground-feeding birds are Galliformes.",
"Herbs used in Middle Eastern dishes are called za'atar.",
"The cities of Meiganga and Guider are in Cameroon.",
"A nutritional supplement used to fight famine is atmit.",
"Statue-menhirs are often found in the western Alps.",
"The album 'Time of Trains' was recorded by Broza.",
"A flap of skin below the jaw is a dewlap.",
"The author of 'Shadows of the Clouds' is Froude.",
"The great falcon of Hungarian folktales is the Turul.",
"The Indian game played on a pyramidal board is pulijudam.",
"The imperial capital of Begemder was Gondar.",
"Long white garments worn by priests are albs.",
"The Nabataean empire established its capital in Petra.",
"Genghis Khan's primary military strategist was Subutai.",
"A song used in Shipibo healing ceremonies is an icaro.",
"'Life Goes On' is a series about the Thatchers.",
"The composer of 'Regarding Faustus' is Gifford.",
"Cultural deformations which remove cranial bone are trephinations.",
"A brown pigment made from wood soot is bistre.",
"In Mutt and Jeff comics, Mutt's son was named Cicero.",
"Misapplication of a word is called catachresis.",
"The sculptor who created art for the Nazi Party is Breker.",
"Eversions of the foot require the subtalar joint.",
"A game that uses a board and dragon tower pieces is kamisado.",
"The Scottish term for theft using force is stouthrief.",
"Kicking a rugby ball so that it bounces is a grubber.",
"A flaky deposit found in port bottles is beeswing.",
"The body of a rotten tree is called a daddock.",
"The quote 'Hardship makes the world obscure' is by DeLillo.",
"The study of degeneration in a species' offspring is cacogenics.",
"The Sri Lankan flag has four bo leaves.",
"The element named for a Scandinavian city is thulium.",
"A plant that pales due to lack of sun is called etiolated.",
"The first European to navigate California's coast was Cabrillo.",
"Growth occurs due to increased cell size in auxesis.",
"The first known Masonic text is the Regius Manuscript.",
"The group that created Adinkra symbols is called Akan.",
"Loss of eyelashes or eyebrows is madarosis.",
"A temperate region of taiga is termed boreal.",
"A unit for measuring pain intensity is the dol.",
"The last sound in a word is called the auslaut.",
"The word for a vast desert sand dune is draa.",
"The only split national capital is Nicosia.",
"The provinces of Attapu and Salavan are in Laos.",
"A bony external plate on an animal is a scutum.",
"A lustrum in ancient Roman culture consisted of five years.",
"A 32-card trick-taking game in France is called belote.",
"The national sport of Afghanistan is buzkashi.",
"Small barriers used to trap fish are weirs.",
"Latvia and Saaremaa are separated by the Irbe Strait.",
"The separation of bones without fracture is diastasis.",
"Emaciation due to protein deficiency is called marasmus.",
"Cohn was one of the first modern bacteriologists.",
"A cubic meter of cordwood is a stere.",
"The Global Seed Vault is located underground in Svalbard.",
"The largest lake in Alaska is Iliamna Lake.",
"The feather tuft of a heron is an aigrette.",
"The Cuban Ten Years' War ended with the Pact of Zanjón.",
"A fortnight in the Hindu lunar calendar is a paksha.",
"The gill of a mushroom is called a lamella.",
"Peddlers who sell religious books are colporteurs.",
"Indigenous pygmy groups in Congo are called Mbuti.",
"The Jupiter moon named for a Cyprian nymph is Himalia.",
"An agent that kills tapeworms is a taeniacide.",
"The Pulitzer Prize in fiction in 1967 went to Malamud.",
"The spinal nerve that projects from the pinky is C8.",
"The ogres of Burmese folklore are bilus.",
"Rock that forms by lithification of volcanic ash is ignimbrite.",
"The reflecting power of a surface is its albedo.",
"The anchoring point near a harbor is a roadstead.",
"A skipping rope forms a curve called a troposkein.",
"Surfaces bounded by two intersecting arcs are lunes.",
"The Buddhist practice of warding off misfortune is paritta.",
"The Svedberg unit is used for sedimentation rates.",
"Chicha morada is made with fermented maize.",
"The deflection seen in rotating reference frames is Coriolis force.",
"The first female president of the Philippines was Aquino.",
"A joint permitting free movement is a diarthrosis.",
"An ornament that hides roof joints is an antefix.",
"One court dance with French origins is the passepied.",
"The man who first completed a parachute jump was Garnerin.",
"During the Meiji era, Japan was ruled by Mutsuhito.",
"An actor who suffered from spina bifida is Kirby.",
"Frank Epperson invented the first Popsicle.",
"The author of the science fiction poem 'Aniara' is Martinson.",
"The scientist who developed the phlogiston theory is Becher.",
"An object shaped like a bean is fabiform.",
"One famous ventriloquist and comedian is Strassman.",
"Akita Kantō is a Japanese festival held every August.",
"A wicker boat covered with skin is a coracle.",
"The bird nicknamed 'stinkbird' is the hoatzin.",
"A Finnish gift-giving Christmas figure is Joulupukki.",
"The director of 'Stranger than Paradise' is Jarmusch.",
"A light whose rays are parallel is collimated.",
"Queah is a two-player Liberian boardgame.",
"The Aral Sea island that became a peninsula is Vozrozhdeniya.",
"The German colony in modern-day Kenya was Wituland.",
"The Armenian goddess who personifies Earth is Aretia.",
"The scientist who showed that cells compose organisms is Schleiden.",
"Unburned tobacco left in a pipe is a dottle.",
"The capital of Tuvalu is called Funafuti.",
"Mana whakatipu is Maori for 'power from leadership.'",
"The capital city of Timor-Leste is called Dili.",
"The neurological term for lack of motivation is abulia.",
"The last battle of the Anglo-Zulu war was in Ulundi.",
"The approximate length of a forearm is a cubit.",
"The oil secreted by the tarsal glands is meibum.",
"The highest mountain in South America is Aconcagua.",
"The laxative extracted from cucumbers is elaterium.",
"A gathering of males for a mating display is a lek.",
"The Iori river passes through the nation of Azerbaijan.",
"The island known for its Jellyfish Lake is Mecherchar.",
"Kurgan burials are remnants of ancient Pazyryk culture. ",
"The city nicknamed the Peace Arch City is Blaine.",
"Tellurium boils at approximately 1261 degrees Kelvin.",
"Psittacosis is passed to humans via bird droppings.",
"Eagle syndrome is caused by a calcified ligament.",
"Electrically weak particles emitted in beta decay are neutrinos.",
"The Swati language belongs to the Niger-Congo family.",
"Caprivi is a region located in Namibia.",
"The competitive toxin release by animals is allelopathy.",
"'Make Hay While the Sun Shines' was composed by Sedgwick.",
"The layer of loose material covering bedrock is regolith.",
"The capital city of Turkmenistan is called Ashgabat.",
"A device used to create blackbody radiation is a hohlraum.",
"The first name of Tertius Lydgate's vain wife is Rosamond.",
"The study of butterflies and moths is lepidopterology.",
"The plant that grows frost-tolerant blooms is the eranthis.",
"The principle component of mica is potassium aluminosilicate.",
"Masahiro Andoh was part of the band T-Square.",
"A flat-topped submerged mountain is called a guyot.",
"Badgers' underground dens are called setts.",
"The inhabitable part of the world is the ecumene.",
"The fusion of the two clavicles in birds is the furcula.",
"A baud corresponds to one downloaded bit per second.",
"A Puerto Rican word for mountain-dwelling peasants is Jíbaro.",
"Instruments that trace and scale images are pantographs.",
"The pear-shaped string instrument in Arabic music is the oud.",
"Omani culture includes a weapon dance called Razha.",
"The technical term for young alpacas is crias.",
"One dish made with steamed bananas is matoke.",
"The first nation to ratify the United Nations charter was Nicaragua.",
"The country with the most Nobel winners per capita is Iceland.",
"The tallest mountain on the planet Mercury is Caloris Montes.",
"The second deepest lake in Africa is Lake Malawi.",
"The longest glacier in Mongolia is Potanin Glacier.",
"A group of owls is called a parliament.",
"A group of crabs is called a consortium.",
"The first female member of the LAPD was Wells.",
"The tallest mountain on Antarctica is Vinson Massif.",
"The longest river in Thailand is the Chi River.",
"The second largest city in Nepal is Biratnagar.",
"The tallest waterfall in Alberta Canada is Panther Falls.",
"The northernmost city in Siberia is Norilsk.",
"The indigenous people of the far north of Sweden are the Sami.",
"The third largest landlocked country by area is Chad.",
"The Zanj Revolution occurred in present day Iraq.",
"The hollow shaft of a feather is a calamus.",
"Heelless leather slippers worn in Morocco are balgha.",
"Load-carrying beams in a timber house are bressummers.",
"The first Barbie doll was designed by Handler.",
"A group of baboons is called a flange.",
"Impaired sense of taste is called ageusia.",
"Depression following a nightmare is malneirophrenia.",
"The river that divides Venezuela and Colombia is the Orinoco.",
"The smallest fish species is the paedocypris.",
"Sirikwa holes were used as pens for cattle.",
"Derby shoes are sometimes referred to as bluchers.",
"A disease that damages the middle ear is cholesteatoma.",
"The geological formation of continents is epeirogeny.",
"One famous woman who co-founded the NAACP was Ovington.",
"This is an attention check. Press 1 to continue.",
"This is an attention check. Press 2 to continue.",
"This is an attention check. Press 3 to continue.",
"This is an attention check. Press 4 to continue.",
"This is an attention check. Press 5 to continue.",
"This is an attention check. Press 6 to continue.",
"This is an attention check. Press 5 to continue.",
"This is an attention check. Press 4 to continue.",
"This is an attention check. Press 3 to continue.",
"This is an attention check. Press 2 to continue."]
